//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu
    {
        public System.Guid MenuId { get; set; }
        public Nullable<int> MenuNo { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ParentMenuId { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public string MenuIconUrl { get; set; }
        public Nullable<bool> IsVisibal { get; set; }
        public Nullable<bool> IsLeaf { get; set; }
    }
}
